// Copyright (c) 2024 The BitFS developers
// Use of this source code is governed by the Open BSV License v5
// that can be found in the LICENSE file.

// Package banner renders the BitFS CLI startup banner with gradient colors.
package banner

import (
	"fmt"
	"os"
	"strings"
)

// ASCII art generated by figlet with "ANSI Shadow" font.
const bitfsArt = "" +
	"██████╗ ██╗████████╗███████╗███████╗\n" +
	"██╔══██╗██║╚══██╔══╝██╔════╝██╔════╝\n" +
	"██████╔╝██║   ██║   █████╗  ███████╗\n" +
	"██╔══██╗██║   ██║   ██╔══╝  ╚════██║\n" +
	"██████╔╝██║   ██║   ██║     ███████║\n" +
	"╚═════╝ ╚═╝   ╚═╝   ╚═╝     ╚══════╝"

// Botanical gradient from BitFS VI system: gold-dark → gold → gold-light.
var gradient = [][3]int{
	{0xa0, 0x75, 0x48}, // #a07548
	{0xc9, 0x95, 0x6b}, // #c9956b
	{0xdb, 0xb0, 0x8a}, // #dbb08a
}

func interpolate(t float64) (int, int, int) {
	if t <= 0 {
		return gradient[0][0], gradient[0][1], gradient[0][2]
	}
	if t >= 1 {
		return gradient[len(gradient)-1][0], gradient[len(gradient)-1][1], gradient[len(gradient)-1][2]
	}
	segments := float64(len(gradient) - 1)
	scaled := t * segments
	idx := int(scaled)
	if idx >= len(gradient)-1 {
		idx = len(gradient) - 2
	}
	f := scaled - float64(idx)
	r := int(float64(gradient[idx][0]) + (float64(gradient[idx+1][0])-float64(gradient[idx][0]))*f)
	g := int(float64(gradient[idx][1]) + (float64(gradient[idx+1][1])-float64(gradient[idx][1]))*f)
	b := int(float64(gradient[idx][2]) + (float64(gradient[idx+1][2])-float64(gradient[idx][2]))*f)
	return r, g, b
}

func applyGradient(text string) string {
	lines := strings.Split(text, "\n")
	// Find max rune width for consistent gradient across lines.
	maxWidth := 0
	for _, line := range lines {
		if w := len([]rune(line)); w > maxWidth {
			maxWidth = w
		}
	}
	if maxWidth == 0 {
		return text
	}

	var sb strings.Builder
	for i, line := range lines {
		runes := []rune(line)
		for j, r := range runes {
			t := float64(j) / float64(maxWidth-1)
			cr, cg, cb := interpolate(t)
			fmt.Fprintf(&sb, "\033[38;2;%d;%d;%dm%c", cr, cg, cb, r)
		}
		sb.WriteString("\033[0m")
		if i < len(lines)-1 {
			sb.WriteByte('\n')
		}
	}
	return sb.String()
}

const (
	dimColor  = "\033[38;2;140;130;118m"
	textColor = "\033[38;2;212;205;196m"
	reset     = "\033[0m"
)

// Print renders the BitFS banner to stderr.
func Print(version string) {
	fmt.Fprint(os.Stderr, "\n")
	fmt.Fprintln(os.Stderr, applyGradient(bitfsArt))
	fmt.Fprintf(os.Stderr, "%s  Decentralized Encrypted File System%s  %sv%s%s\n", textColor, reset, dimColor, version, reset)
	fmt.Fprintf(os.Stderr, "%s  https://bitfs.org%s\n\n", dimColor, reset)
}
